/*
 * generated by Xtext 2.23.0
 */
package game.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import game.ide.contentassist.antlr.internal.InternalGameParser;
import game.services.GameGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GameParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GameGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GameGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getElementsJeuAccess().getAlternatives(), "rule__ElementsJeu__Alternatives");
			builder.put(grammarAccess.getPlaceAccess().getAlternatives(), "rule__Place__Alternatives");
			builder.put(grammarAccess.getAvantageAccess().getAlternatives(), "rule__Avantage__Alternatives");
			builder.put(grammarAccess.getChoixAccess().getAlternatives_5_0(), "rule__Choix__Alternatives_5_0");
			builder.put(grammarAccess.getConditionAccess().getAlternatives(), "rule__Condition__Alternatives");
			builder.put(grammarAccess.getConditionAccess().getAlternatives_0_3_1(), "rule__Condition__Alternatives_0_3_1");
			builder.put(grammarAccess.getConditionAccess().getAlternatives_0_4_2(), "rule__Condition__Alternatives_0_4_2");
			builder.put(grammarAccess.getNatureAccess().getAlternatives(), "rule__Nature__Alternatives");
			builder.put(grammarAccess.getJeuAccess().getGroup(), "rule__Jeu__Group__0");
			builder.put(grammarAccess.getTerritoireAccess().getGroup(), "rule__Territoire__Group__0");
			builder.put(grammarAccess.getLieuAccess().getGroup(), "rule__Lieu__Group__0");
			builder.put(grammarAccess.getCheminAccess().getGroup(), "rule__Chemin__Group__0");
			builder.put(grammarAccess.getPersonneAccess().getGroup(), "rule__Personne__Group__0");
			builder.put(grammarAccess.getExplorateurAccess().getGroup(), "rule__Explorateur__Group__0");
			builder.put(grammarAccess.getExplorateurAccess().getGroup_7(), "rule__Explorateur__Group_7__0");
			builder.put(grammarAccess.getExplorateurAccess().getGroup_8(), "rule__Explorateur__Group_8__0");
			builder.put(grammarAccess.getConnaissanceAccess().getGroup(), "rule__Connaissance__Group__0");
			builder.put(grammarAccess.getObjetAccess().getGroup(), "rule__Objet__Group__0");
			builder.put(grammarAccess.getInteractionAccess().getGroup(), "rule__Interaction__Group__0");
			builder.put(grammarAccess.getChoixAccess().getGroup(), "rule__Choix__Group__0");
			builder.put(grammarAccess.getChoixAccess().getGroup_5(), "rule__Choix__Group_5__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_0(), "rule__Condition__Group_0__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_0_3(), "rule__Condition__Group_0_3__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_0_3_1_0(), "rule__Condition__Group_0_3_1_0__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_0_3_1_1(), "rule__Condition__Group_0_3_1_1__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_0_4(), "rule__Condition__Group_0_4__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_0_4_2_0(), "rule__Condition__Group_0_4_2_0__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_0_4_2_1(), "rule__Condition__Group_0_4_2_1__0");
			builder.put(grammarAccess.getJeuAccess().getNameAssignment_1(), "rule__Jeu__NameAssignment_1");
			builder.put(grammarAccess.getJeuAccess().getTerritoireAssignment_3(), "rule__Jeu__TerritoireAssignment_3");
			builder.put(grammarAccess.getJeuAccess().getExplorateurAssignment_4(), "rule__Jeu__ExplorateurAssignment_4");
			builder.put(grammarAccess.getJeuAccess().getElementsjeuAssignment_5(), "rule__Jeu__ElementsjeuAssignment_5");
			builder.put(grammarAccess.getTerritoireAccess().getPlacesAssignment_2(), "rule__Territoire__PlacesAssignment_2");
			builder.put(grammarAccess.getLieuAccess().getNameAssignment_1(), "rule__Lieu__NameAssignment_1");
			builder.put(grammarAccess.getLieuAccess().getNatureAssignment_3(), "rule__Lieu__NatureAssignment_3");
			builder.put(grammarAccess.getCheminAccess().getNameAssignment_1(), "rule__Chemin__NameAssignment_1");
			builder.put(grammarAccess.getCheminAccess().getPredAssignment_4(), "rule__Chemin__PredAssignment_4");
			builder.put(grammarAccess.getCheminAccess().getSuccAssignment_6(), "rule__Chemin__SuccAssignment_6");
			builder.put(grammarAccess.getCheminAccess().getVisibleAssignment_8(), "rule__Chemin__VisibleAssignment_8");
			builder.put(grammarAccess.getCheminAccess().getObligatoireAssignment_10(), "rule__Chemin__ObligatoireAssignment_10");
			builder.put(grammarAccess.getCheminAccess().getOuvertAssignment_12(), "rule__Chemin__OuvertAssignment_12");
			builder.put(grammarAccess.getPersonneAccess().getNameAssignment_1(), "rule__Personne__NameAssignment_1");
			builder.put(grammarAccess.getPersonneAccess().getPlaceAssignment_4(), "rule__Personne__PlaceAssignment_4");
			builder.put(grammarAccess.getPersonneAccess().getVisibleAssignment_6(), "rule__Personne__VisibleAssignment_6");
			builder.put(grammarAccess.getPersonneAccess().getActifAssignment_8(), "rule__Personne__ActifAssignment_8");
			builder.put(grammarAccess.getPersonneAccess().getObligatoireAssignment_10(), "rule__Personne__ObligatoireAssignment_10");
			builder.put(grammarAccess.getPersonneAccess().getInteractionsAssignment_12(), "rule__Personne__InteractionsAssignment_12");
			builder.put(grammarAccess.getExplorateurAccess().getPlaceAssignment_3(), "rule__Explorateur__PlaceAssignment_3");
			builder.put(grammarAccess.getExplorateurAccess().getTailleDispoAssignment_6(), "rule__Explorateur__TailleDispoAssignment_6");
			builder.put(grammarAccess.getExplorateurAccess().getObjetsAssignment_7_2(), "rule__Explorateur__ObjetsAssignment_7_2");
			builder.put(grammarAccess.getExplorateurAccess().getConnaissancesAssignment_8_2(), "rule__Explorateur__ConnaissancesAssignment_8_2");
			builder.put(grammarAccess.getConnaissanceAccess().getNameAssignment_1(), "rule__Connaissance__NameAssignment_1");
			builder.put(grammarAccess.getConnaissanceAccess().getVisibleAssignment_4(), "rule__Connaissance__VisibleAssignment_4");
			builder.put(grammarAccess.getConnaissanceAccess().getActifAssignment_6(), "rule__Connaissance__ActifAssignment_6");
			builder.put(grammarAccess.getObjetAccess().getNameAssignment_1(), "rule__Objet__NameAssignment_1");
			builder.put(grammarAccess.getObjetAccess().getVisibleAssignment_4(), "rule__Objet__VisibleAssignment_4");
			builder.put(grammarAccess.getObjetAccess().getActifAssignment_6(), "rule__Objet__ActifAssignment_6");
			builder.put(grammarAccess.getObjetAccess().getQteAssignment_8(), "rule__Objet__QteAssignment_8");
			builder.put(grammarAccess.getObjetAccess().getTailleAssignment_10(), "rule__Objet__TailleAssignment_10");
			builder.put(grammarAccess.getObjetAccess().getTransformableAssignment_12(), "rule__Objet__TransformableAssignment_12");
			builder.put(grammarAccess.getInteractionAccess().getQuestionAssignment_3(), "rule__Interaction__QuestionAssignment_3");
			builder.put(grammarAccess.getInteractionAccess().getChoixAssignment_4(), "rule__Interaction__ChoixAssignment_4");
			builder.put(grammarAccess.getChoixAccess().getNumeroAssignment_1(), "rule__Choix__NumeroAssignment_1");
			builder.put(grammarAccess.getChoixAccess().getReponseAssignment_4(), "rule__Choix__ReponseAssignment_4");
			builder.put(grammarAccess.getChoixAccess().getQteAssignment_5_1(), "rule__Choix__QteAssignment_5_1");
			builder.put(grammarAccess.getChoixAccess().getAvantageAssignment_5_2(), "rule__Choix__AvantageAssignment_5_2");
			builder.put(grammarAccess.getConditionAccess().getNameAssignment_0_1(), "rule__Condition__NameAssignment_0_1");
			builder.put(grammarAccess.getConditionAccess().getConnaissancesRequisesAssignment_0_3_1_0_1(), "rule__Condition__ConnaissancesRequisesAssignment_0_3_1_0_1");
			builder.put(grammarAccess.getConditionAccess().getConnaissancesInterditesAssignment_0_3_1_1_1(), "rule__Condition__ConnaissancesInterditesAssignment_0_3_1_1_1");
			builder.put(grammarAccess.getConditionAccess().getQuantiteAssignment_0_4_0(), "rule__Condition__QuantiteAssignment_0_4_0");
			builder.put(grammarAccess.getConditionAccess().getObjetsRequisAssignment_0_4_2_0_1(), "rule__Condition__ObjetsRequisAssignment_0_4_2_0_1");
			builder.put(grammarAccess.getConditionAccess().getObjetsInterditsAssignment_0_4_2_1_1(), "rule__Condition__ObjetsInterditsAssignment_0_4_2_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GameGrammarAccess grammarAccess;

	@Override
	protected InternalGameParser createParser() {
		InternalGameParser result = new InternalGameParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
