/**
 * generated by Xtext 2.23.0
 */
package game.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.game.Condition#getConnaissancesRequises <em>Connaissances Requises</em>}</li>
 *   <li>{@link game.game.Condition#getObjetsRequis <em>Objets Requis</em>}</li>
 * </ul>
 *
 * @see game.game.GamePackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Connaissances Requises</b></em>' containment reference list.
   * The list contents are of type {@link game.game.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissances Requises</em>' containment reference list.
   * @see game.game.GamePackage#getCondition_ConnaissancesRequises()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getConnaissancesRequises();

  /**
   * Returns the value of the '<em><b>Objets Requis</b></em>' containment reference list.
   * The list contents are of type {@link game.game.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets Requis</em>' containment reference list.
   * @see game.game.GamePackage#getCondition_ObjetsRequis()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjetsRequis();

} // Condition
