/**
 * generated by Xtext 2.23.0
 */
package game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition Personne</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.game.ConditionPersonne#getVisible <em>Visible</em>}</li>
 *   <li>{@link game.game.ConditionPersonne#getActive <em>Active</em>}</li>
 * </ul>
 *
 * @see game.game.GamePackage#getConditionPersonne()
 * @model
 * @generated
 */
public interface ConditionPersonne extends Condition {
	/**
	 * Returns the value of the '<em><b>Visible</b></em>' container reference.
	 * It is bidirectional and its opposite is '{@link game.game.Personne#getVisible <em>Visible</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Visible</em>' container reference.
	 * @see #setVisible(Personne)
	 * @see game.game.GamePackage#getConditionPersonne_Visible()
	 * @see game.game.Personne#getVisible
	 * @model opposite="visible" transient="false"
	 * @generated
	 */
	Personne getVisible();

	/**
	 * Sets the value of the '{@link game.game.ConditionPersonne#getVisible <em>Visible</em>}' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Visible</em>' container reference.
	 * @see #getVisible()
	 * @generated
	 */
	void setVisible(Personne value);

	/**
	 * Returns the value of the '<em><b>Active</b></em>' container reference.
	 * It is bidirectional and its opposite is '{@link game.game.Personne#getActive <em>Active</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Active</em>' container reference.
	 * @see #setActive(Personne)
	 * @see game.game.GamePackage#getConditionPersonne_Active()
	 * @see game.game.Personne#getActive
	 * @model opposite="active" transient="false"
	 * @generated
	 */
	Personne getActive();

	/**
	 * Sets the value of the '{@link game.game.ConditionPersonne#getActive <em>Active</em>}' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Active</em>' container reference.
	 * @see #getActive()
	 * @generated
	 */
	void setActive(Personne value);

} // ConditionPersonne
