/**
 * generated by Xtext 2.23.0
 */
package game.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.game.Condition#getConnaissanceRequise <em>Connaissance Requise</em>}</li>
 *   <li>{@link game.game.Condition#getConnaissanceInterdite <em>Connaissance Interdite</em>}</li>
 *   <li>{@link game.game.Condition#getObjetRequis <em>Objet Requis</em>}</li>
 *   <li>{@link game.game.Condition#getObjetInterdit <em>Objet Interdit</em>}</li>
 * </ul>
 *
 * @see game.game.GamePackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends ElementsJeu
{
  /**
	 * Returns the value of the '<em><b>Connaissance Requise</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Connaissance Requise</em>' reference.
	 * @see #setConnaissanceRequise(Connaissance)
	 * @see game.game.GamePackage#getCondition_ConnaissanceRequise()
	 * @model
	 * @generated
	 */
	Connaissance getConnaissanceRequise();

	/**
	 * Sets the value of the '{@link game.game.Condition#getConnaissanceRequise <em>Connaissance Requise</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Connaissance Requise</em>' reference.
	 * @see #getConnaissanceRequise()
	 * @generated
	 */
	void setConnaissanceRequise(Connaissance value);

	/**
	 * Returns the value of the '<em><b>Connaissance Interdite</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Connaissance Interdite</em>' reference.
	 * @see #setConnaissanceInterdite(Connaissance)
	 * @see game.game.GamePackage#getCondition_ConnaissanceInterdite()
	 * @model
	 * @generated
	 */
	Connaissance getConnaissanceInterdite();

	/**
	 * Sets the value of the '{@link game.game.Condition#getConnaissanceInterdite <em>Connaissance Interdite</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Connaissance Interdite</em>' reference.
	 * @see #getConnaissanceInterdite()
	 * @generated
	 */
	void setConnaissanceInterdite(Connaissance value);

	/**
	 * Returns the value of the '<em><b>Objet Requis</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Objet Requis</em>' reference.
	 * @see #setObjetRequis(QteObjet)
	 * @see game.game.GamePackage#getCondition_ObjetRequis()
	 * @model
	 * @generated
	 */
	QteObjet getObjetRequis();

	/**
	 * Sets the value of the '{@link game.game.Condition#getObjetRequis <em>Objet Requis</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Objet Requis</em>' reference.
	 * @see #getObjetRequis()
	 * @generated
	 */
	void setObjetRequis(QteObjet value);

	/**
	 * Returns the value of the '<em><b>Objet Interdit</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Objet Interdit</em>' reference.
	 * @see #setObjetInterdit(QteObjet)
	 * @see game.game.GamePackage#getCondition_ObjetInterdit()
	 * @model
	 * @generated
	 */
	QteObjet getObjetInterdit();

	/**
	 * Sets the value of the '{@link game.game.Condition#getObjetInterdit <em>Objet Interdit</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Objet Interdit</em>' reference.
	 * @see #getObjetInterdit()
	 * @generated
	 */
	void setObjetInterdit(QteObjet value);

} // Condition
