/**
 * generated by Xtext 2.23.0
 */
package game.game;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see game.game.GameFactory
 * @model kind="package"
 * @generated
 */
public interface GamePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "game";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Game.game";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "game";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GamePackage eINSTANCE = game.game.impl.GamePackageImpl.init();

  /**
   * The meta object id for the '{@link game.game.impl.JeuImpl <em>Jeu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.JeuImpl
   * @see game.game.impl.GamePackageImpl#getJeu()
   * @generated
   */
  int JEU = 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__NOM = 0;

  /**
   * The feature id for the '<em><b>Territoire</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__TERRITOIRE = 1;

  /**
   * The feature id for the '<em><b>Explorateur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__EXPLORATEUR = 2;

  /**
   * The feature id for the '<em><b>Elementsjeu</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__ELEMENTSJEU = 3;

  /**
   * The number of structural features of the '<em>Jeu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link game.game.impl.ElementsJeuImpl <em>Elements Jeu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.ElementsJeuImpl
   * @see game.game.impl.GamePackageImpl#getElementsJeu()
   * @generated
   */
  int ELEMENTS_JEU = 1;

  /**
   * The number of structural features of the '<em>Elements Jeu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTS_JEU_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link game.game.impl.PlaceImpl <em>Place</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.PlaceImpl
   * @see game.game.impl.GamePackageImpl#getPlace()
   * @generated
   */
  int PLACE = 2;

  /**
   * The number of structural features of the '<em>Place</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACE_FEATURE_COUNT = ELEMENTS_JEU_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link game.game.impl.AvantageImpl <em>Avantage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.AvantageImpl
   * @see game.game.impl.GamePackageImpl#getAvantage()
   * @generated
   */
  int AVANTAGE = 3;

  /**
   * The feature id for the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVANTAGE__VISIBLE = ELEMENTS_JEU_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Actif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVANTAGE__ACTIF = ELEMENTS_JEU_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Avantage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVANTAGE_FEATURE_COUNT = ELEMENTS_JEU_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link game.game.impl.TerritoireImpl <em>Territoire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.TerritoireImpl
   * @see game.game.impl.GamePackageImpl#getTerritoire()
   * @generated
   */
  int TERRITOIRE = 4;

  /**
   * The feature id for the '<em><b>Places</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERRITOIRE__PLACES = 0;

  /**
   * The number of structural features of the '<em>Territoire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERRITOIRE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link game.game.impl.LieuImpl <em>Lieu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.LieuImpl
   * @see game.game.impl.GamePackageImpl#getLieu()
   * @generated
   */
  int LIEU = 5;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__NOM = PLACE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Nature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__NATURE = PLACE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Lieu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FEATURE_COUNT = PLACE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link game.game.impl.CheminImpl <em>Chemin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.CheminImpl
   * @see game.game.impl.GamePackageImpl#getChemin()
   * @generated
   */
  int CHEMIN = 6;

  /**
   * The feature id for the '<em><b>Pred</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__PRED = PLACE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Succ</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__SUCC = PLACE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__VISIBLE = PLACE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Obligatoire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__OBLIGATOIRE = PLACE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Ouvert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__OUVERT = PLACE_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Chemin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN_FEATURE_COUNT = PLACE_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link game.game.impl.PersonneImpl <em>Personne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.PersonneImpl
   * @see game.game.impl.GamePackageImpl#getPersonne()
   * @generated
   */
  int PERSONNE = 7;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__NOM = ELEMENTS_JEU_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__VISIBLE = ELEMENTS_JEU_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Actif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__ACTIF = ELEMENTS_JEU_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Obligatoire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__OBLIGATOIRE = ELEMENTS_JEU_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Interactions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__INTERACTIONS = ELEMENTS_JEU_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Personne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE_FEATURE_COUNT = ELEMENTS_JEU_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link game.game.impl.ExplorateurImpl <em>Explorateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.ExplorateurImpl
   * @see game.game.impl.GamePackageImpl#getExplorateur()
   * @generated
   */
  int EXPLORATEUR = 8;

  /**
   * The feature id for the '<em><b>Place</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__PLACE = 0;

  /**
   * The feature id for the '<em><b>Taille Dispo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__TAILLE_DISPO = 1;

  /**
   * The feature id for the '<em><b>Objets</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__OBJETS = 2;

  /**
   * The feature id for the '<em><b>Connaissances</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__CONNAISSANCES = 3;

  /**
   * The number of structural features of the '<em>Explorateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link game.game.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.ConnaissanceImpl
   * @see game.game.impl.GamePackageImpl#getConnaissance()
   * @generated
   */
  int CONNAISSANCE = 9;

  /**
   * The feature id for the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__VISIBLE = AVANTAGE__VISIBLE;

  /**
   * The feature id for the '<em><b>Actif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__ACTIF = AVANTAGE__ACTIF;

  /**
   * The number of structural features of the '<em>Connaissance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE_FEATURE_COUNT = AVANTAGE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link game.game.impl.ObjetImpl <em>Objet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.ObjetImpl
   * @see game.game.impl.GamePackageImpl#getObjet()
   * @generated
   */
  int OBJET = 10;

  /**
   * The feature id for the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__VISIBLE = AVANTAGE__VISIBLE;

  /**
   * The feature id for the '<em><b>Actif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__ACTIF = AVANTAGE__ACTIF;

  /**
   * The feature id for the '<em><b>Qte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__QTE = AVANTAGE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__TAILLE = AVANTAGE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Transformable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__TRANSFORMABLE = AVANTAGE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Objet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_FEATURE_COUNT = AVANTAGE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link game.game.impl.InteractionImpl <em>Interaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.InteractionImpl
   * @see game.game.impl.GamePackageImpl#getInteraction()
   * @generated
   */
  int INTERACTION = 11;

  /**
   * The feature id for the '<em><b>Question</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__QUESTION = 0;

  /**
   * The feature id for the '<em><b>Choix</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__CHOIX = 1;

  /**
   * The number of structural features of the '<em>Interaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link game.game.impl.ChoixImpl <em>Choix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.ChoixImpl
   * @see game.game.impl.GamePackageImpl#getChoix()
   * @generated
   */
  int CHOIX = 12;

  /**
   * The feature id for the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__NUMERO = 0;

  /**
   * The feature id for the '<em><b>Reponse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__REPONSE = 1;

  /**
   * The feature id for the '<em><b>Recompense</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__RECOMPENSE = 2;

  /**
   * The number of structural features of the '<em>Choix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link game.game.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.ConditionImpl
   * @see game.game.impl.GamePackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 13;

  /**
   * The feature id for the '<em><b>Connaissances Requises</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONNAISSANCES_REQUISES = 0;

  /**
   * The feature id for the '<em><b>Objets Requis</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__OBJETS_REQUIS = 1;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link game.game.impl.RecompenseImpl <em>Recompense</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.impl.RecompenseImpl
   * @see game.game.impl.GamePackageImpl#getRecompense()
   * @generated
   */
  int RECOMPENSE = 14;

  /**
   * The feature id for the '<em><b>Avantage</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECOMPENSE__AVANTAGE = 0;

  /**
   * The number of structural features of the '<em>Recompense</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECOMPENSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link game.game.Nature <em>Nature</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.game.Nature
   * @see game.game.impl.GamePackageImpl#getNature()
   * @generated
   */
  int NATURE = 15;


  /**
   * Returns the meta object for class '{@link game.game.Jeu <em>Jeu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Jeu</em>'.
   * @see game.game.Jeu
   * @generated
   */
  EClass getJeu();

  /**
   * Returns the meta object for the attribute '{@link game.game.Jeu#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see game.game.Jeu#getNom()
   * @see #getJeu()
   * @generated
   */
  EAttribute getJeu_Nom();

  /**
   * Returns the meta object for the containment reference '{@link game.game.Jeu#getTerritoire <em>Territoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Territoire</em>'.
   * @see game.game.Jeu#getTerritoire()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Territoire();

  /**
   * Returns the meta object for the containment reference '{@link game.game.Jeu#getExplorateur <em>Explorateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Explorateur</em>'.
   * @see game.game.Jeu#getExplorateur()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Explorateur();

  /**
   * Returns the meta object for the containment reference list '{@link game.game.Jeu#getElementsjeu <em>Elementsjeu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elementsjeu</em>'.
   * @see game.game.Jeu#getElementsjeu()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Elementsjeu();

  /**
   * Returns the meta object for class '{@link game.game.ElementsJeu <em>Elements Jeu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elements Jeu</em>'.
   * @see game.game.ElementsJeu
   * @generated
   */
  EClass getElementsJeu();

  /**
   * Returns the meta object for class '{@link game.game.Place <em>Place</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Place</em>'.
   * @see game.game.Place
   * @generated
   */
  EClass getPlace();

  /**
   * Returns the meta object for class '{@link game.game.Avantage <em>Avantage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Avantage</em>'.
   * @see game.game.Avantage
   * @generated
   */
  EClass getAvantage();

  /**
   * Returns the meta object for the attribute '{@link game.game.Avantage#isVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visible</em>'.
   * @see game.game.Avantage#isVisible()
   * @see #getAvantage()
   * @generated
   */
  EAttribute getAvantage_Visible();

  /**
   * Returns the meta object for the attribute '{@link game.game.Avantage#isActif <em>Actif</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Actif</em>'.
   * @see game.game.Avantage#isActif()
   * @see #getAvantage()
   * @generated
   */
  EAttribute getAvantage_Actif();

  /**
   * Returns the meta object for class '{@link game.game.Territoire <em>Territoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Territoire</em>'.
   * @see game.game.Territoire
   * @generated
   */
  EClass getTerritoire();

  /**
   * Returns the meta object for the containment reference list '{@link game.game.Territoire#getPlaces <em>Places</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Places</em>'.
   * @see game.game.Territoire#getPlaces()
   * @see #getTerritoire()
   * @generated
   */
  EReference getTerritoire_Places();

  /**
   * Returns the meta object for class '{@link game.game.Lieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lieu</em>'.
   * @see game.game.Lieu
   * @generated
   */
  EClass getLieu();

  /**
   * Returns the meta object for the attribute '{@link game.game.Lieu#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see game.game.Lieu#getNom()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Nom();

  /**
   * Returns the meta object for the attribute '{@link game.game.Lieu#getNature <em>Nature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nature</em>'.
   * @see game.game.Lieu#getNature()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Nature();

  /**
   * Returns the meta object for class '{@link game.game.Chemin <em>Chemin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chemin</em>'.
   * @see game.game.Chemin
   * @generated
   */
  EClass getChemin();

  /**
   * Returns the meta object for the reference '{@link game.game.Chemin#getPred <em>Pred</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pred</em>'.
   * @see game.game.Chemin#getPred()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Pred();

  /**
   * Returns the meta object for the reference '{@link game.game.Chemin#getSucc <em>Succ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Succ</em>'.
   * @see game.game.Chemin#getSucc()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Succ();

  /**
   * Returns the meta object for the attribute '{@link game.game.Chemin#isVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visible</em>'.
   * @see game.game.Chemin#isVisible()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Visible();

  /**
   * Returns the meta object for the attribute '{@link game.game.Chemin#isObligatoire <em>Obligatoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obligatoire</em>'.
   * @see game.game.Chemin#isObligatoire()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Obligatoire();

  /**
   * Returns the meta object for the attribute '{@link game.game.Chemin#isOuvert <em>Ouvert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ouvert</em>'.
   * @see game.game.Chemin#isOuvert()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Ouvert();

  /**
   * Returns the meta object for class '{@link game.game.Personne <em>Personne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Personne</em>'.
   * @see game.game.Personne
   * @generated
   */
  EClass getPersonne();

  /**
   * Returns the meta object for the attribute '{@link game.game.Personne#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see game.game.Personne#getNom()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Nom();

  /**
   * Returns the meta object for the attribute '{@link game.game.Personne#isVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visible</em>'.
   * @see game.game.Personne#isVisible()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Visible();

  /**
   * Returns the meta object for the attribute '{@link game.game.Personne#isActif <em>Actif</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Actif</em>'.
   * @see game.game.Personne#isActif()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Actif();

  /**
   * Returns the meta object for the attribute '{@link game.game.Personne#isObligatoire <em>Obligatoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obligatoire</em>'.
   * @see game.game.Personne#isObligatoire()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Obligatoire();

  /**
   * Returns the meta object for the containment reference list '{@link game.game.Personne#getInteractions <em>Interactions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Interactions</em>'.
   * @see game.game.Personne#getInteractions()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_Interactions();

  /**
   * Returns the meta object for class '{@link game.game.Explorateur <em>Explorateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Explorateur</em>'.
   * @see game.game.Explorateur
   * @generated
   */
  EClass getExplorateur();

  /**
   * Returns the meta object for the containment reference '{@link game.game.Explorateur#getPlace <em>Place</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Place</em>'.
   * @see game.game.Explorateur#getPlace()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Place();

  /**
   * Returns the meta object for the attribute '{@link game.game.Explorateur#getTailleDispo <em>Taille Dispo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille Dispo</em>'.
   * @see game.game.Explorateur#getTailleDispo()
   * @see #getExplorateur()
   * @generated
   */
  EAttribute getExplorateur_TailleDispo();

  /**
   * Returns the meta object for the containment reference '{@link game.game.Explorateur#getObjets <em>Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Objets</em>'.
   * @see game.game.Explorateur#getObjets()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Objets();

  /**
   * Returns the meta object for the containment reference '{@link game.game.Explorateur#getConnaissances <em>Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Connaissances</em>'.
   * @see game.game.Explorateur#getConnaissances()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Connaissances();

  /**
   * Returns the meta object for class '{@link game.game.Connaissance <em>Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connaissance</em>'.
   * @see game.game.Connaissance
   * @generated
   */
  EClass getConnaissance();

  /**
   * Returns the meta object for class '{@link game.game.Objet <em>Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objet</em>'.
   * @see game.game.Objet
   * @generated
   */
  EClass getObjet();

  /**
   * Returns the meta object for the attribute '{@link game.game.Objet#getQte <em>Qte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Qte</em>'.
   * @see game.game.Objet#getQte()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Qte();

  /**
   * Returns the meta object for the attribute '{@link game.game.Objet#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see game.game.Objet#getTaille()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Taille();

  /**
   * Returns the meta object for the attribute '{@link game.game.Objet#isTransformable <em>Transformable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Transformable</em>'.
   * @see game.game.Objet#isTransformable()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Transformable();

  /**
   * Returns the meta object for class '{@link game.game.Interaction <em>Interaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interaction</em>'.
   * @see game.game.Interaction
   * @generated
   */
  EClass getInteraction();

  /**
   * Returns the meta object for the attribute '{@link game.game.Interaction#getQuestion <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Question</em>'.
   * @see game.game.Interaction#getQuestion()
   * @see #getInteraction()
   * @generated
   */
  EAttribute getInteraction_Question();

  /**
   * Returns the meta object for the containment reference list '{@link game.game.Interaction#getChoix <em>Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choix</em>'.
   * @see game.game.Interaction#getChoix()
   * @see #getInteraction()
   * @generated
   */
  EReference getInteraction_Choix();

  /**
   * Returns the meta object for class '{@link game.game.Choix <em>Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choix</em>'.
   * @see game.game.Choix
   * @generated
   */
  EClass getChoix();

  /**
   * Returns the meta object for the attribute '{@link game.game.Choix#getNumero <em>Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero</em>'.
   * @see game.game.Choix#getNumero()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Numero();

  /**
   * Returns the meta object for the attribute '{@link game.game.Choix#getReponse <em>Reponse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reponse</em>'.
   * @see game.game.Choix#getReponse()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Reponse();

  /**
   * Returns the meta object for the containment reference '{@link game.game.Choix#getRecompense <em>Recompense</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Recompense</em>'.
   * @see game.game.Choix#getRecompense()
   * @see #getChoix()
   * @generated
   */
  EReference getChoix_Recompense();

  /**
   * Returns the meta object for class '{@link game.game.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see game.game.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference list '{@link game.game.Condition#getConnaissancesRequises <em>Connaissances Requises</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Connaissances Requises</em>'.
   * @see game.game.Condition#getConnaissancesRequises()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_ConnaissancesRequises();

  /**
   * Returns the meta object for the containment reference list '{@link game.game.Condition#getObjetsRequis <em>Objets Requis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objets Requis</em>'.
   * @see game.game.Condition#getObjetsRequis()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_ObjetsRequis();

  /**
   * Returns the meta object for class '{@link game.game.Recompense <em>Recompense</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recompense</em>'.
   * @see game.game.Recompense
   * @generated
   */
  EClass getRecompense();

  /**
   * Returns the meta object for the containment reference list '{@link game.game.Recompense#getAvantage <em>Avantage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Avantage</em>'.
   * @see game.game.Recompense#getAvantage()
   * @see #getRecompense()
   * @generated
   */
  EReference getRecompense_Avantage();

  /**
   * Returns the meta object for enum '{@link game.game.Nature <em>Nature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Nature</em>'.
   * @see game.game.Nature
   * @generated
   */
  EEnum getNature();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameFactory getGameFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link game.game.impl.JeuImpl <em>Jeu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.JeuImpl
     * @see game.game.impl.GamePackageImpl#getJeu()
     * @generated
     */
    EClass JEU = eINSTANCE.getJeu();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JEU__NOM = eINSTANCE.getJeu_Nom();

    /**
     * The meta object literal for the '<em><b>Territoire</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__TERRITOIRE = eINSTANCE.getJeu_Territoire();

    /**
     * The meta object literal for the '<em><b>Explorateur</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__EXPLORATEUR = eINSTANCE.getJeu_Explorateur();

    /**
     * The meta object literal for the '<em><b>Elementsjeu</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__ELEMENTSJEU = eINSTANCE.getJeu_Elementsjeu();

    /**
     * The meta object literal for the '{@link game.game.impl.ElementsJeuImpl <em>Elements Jeu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.ElementsJeuImpl
     * @see game.game.impl.GamePackageImpl#getElementsJeu()
     * @generated
     */
    EClass ELEMENTS_JEU = eINSTANCE.getElementsJeu();

    /**
     * The meta object literal for the '{@link game.game.impl.PlaceImpl <em>Place</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.PlaceImpl
     * @see game.game.impl.GamePackageImpl#getPlace()
     * @generated
     */
    EClass PLACE = eINSTANCE.getPlace();

    /**
     * The meta object literal for the '{@link game.game.impl.AvantageImpl <em>Avantage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.AvantageImpl
     * @see game.game.impl.GamePackageImpl#getAvantage()
     * @generated
     */
    EClass AVANTAGE = eINSTANCE.getAvantage();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVANTAGE__VISIBLE = eINSTANCE.getAvantage_Visible();

    /**
     * The meta object literal for the '<em><b>Actif</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVANTAGE__ACTIF = eINSTANCE.getAvantage_Actif();

    /**
     * The meta object literal for the '{@link game.game.impl.TerritoireImpl <em>Territoire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.TerritoireImpl
     * @see game.game.impl.GamePackageImpl#getTerritoire()
     * @generated
     */
    EClass TERRITOIRE = eINSTANCE.getTerritoire();

    /**
     * The meta object literal for the '<em><b>Places</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERRITOIRE__PLACES = eINSTANCE.getTerritoire_Places();

    /**
     * The meta object literal for the '{@link game.game.impl.LieuImpl <em>Lieu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.LieuImpl
     * @see game.game.impl.GamePackageImpl#getLieu()
     * @generated
     */
    EClass LIEU = eINSTANCE.getLieu();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__NOM = eINSTANCE.getLieu_Nom();

    /**
     * The meta object literal for the '<em><b>Nature</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__NATURE = eINSTANCE.getLieu_Nature();

    /**
     * The meta object literal for the '{@link game.game.impl.CheminImpl <em>Chemin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.CheminImpl
     * @see game.game.impl.GamePackageImpl#getChemin()
     * @generated
     */
    EClass CHEMIN = eINSTANCE.getChemin();

    /**
     * The meta object literal for the '<em><b>Pred</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__PRED = eINSTANCE.getChemin_Pred();

    /**
     * The meta object literal for the '<em><b>Succ</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__SUCC = eINSTANCE.getChemin_Succ();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__VISIBLE = eINSTANCE.getChemin_Visible();

    /**
     * The meta object literal for the '<em><b>Obligatoire</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__OBLIGATOIRE = eINSTANCE.getChemin_Obligatoire();

    /**
     * The meta object literal for the '<em><b>Ouvert</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__OUVERT = eINSTANCE.getChemin_Ouvert();

    /**
     * The meta object literal for the '{@link game.game.impl.PersonneImpl <em>Personne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.PersonneImpl
     * @see game.game.impl.GamePackageImpl#getPersonne()
     * @generated
     */
    EClass PERSONNE = eINSTANCE.getPersonne();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__NOM = eINSTANCE.getPersonne_Nom();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__VISIBLE = eINSTANCE.getPersonne_Visible();

    /**
     * The meta object literal for the '<em><b>Actif</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__ACTIF = eINSTANCE.getPersonne_Actif();

    /**
     * The meta object literal for the '<em><b>Obligatoire</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__OBLIGATOIRE = eINSTANCE.getPersonne_Obligatoire();

    /**
     * The meta object literal for the '<em><b>Interactions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__INTERACTIONS = eINSTANCE.getPersonne_Interactions();

    /**
     * The meta object literal for the '{@link game.game.impl.ExplorateurImpl <em>Explorateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.ExplorateurImpl
     * @see game.game.impl.GamePackageImpl#getExplorateur()
     * @generated
     */
    EClass EXPLORATEUR = eINSTANCE.getExplorateur();

    /**
     * The meta object literal for the '<em><b>Place</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__PLACE = eINSTANCE.getExplorateur_Place();

    /**
     * The meta object literal for the '<em><b>Taille Dispo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPLORATEUR__TAILLE_DISPO = eINSTANCE.getExplorateur_TailleDispo();

    /**
     * The meta object literal for the '<em><b>Objets</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__OBJETS = eINSTANCE.getExplorateur_Objets();

    /**
     * The meta object literal for the '<em><b>Connaissances</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__CONNAISSANCES = eINSTANCE.getExplorateur_Connaissances();

    /**
     * The meta object literal for the '{@link game.game.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.ConnaissanceImpl
     * @see game.game.impl.GamePackageImpl#getConnaissance()
     * @generated
     */
    EClass CONNAISSANCE = eINSTANCE.getConnaissance();

    /**
     * The meta object literal for the '{@link game.game.impl.ObjetImpl <em>Objet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.ObjetImpl
     * @see game.game.impl.GamePackageImpl#getObjet()
     * @generated
     */
    EClass OBJET = eINSTANCE.getObjet();

    /**
     * The meta object literal for the '<em><b>Qte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__QTE = eINSTANCE.getObjet_Qte();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__TAILLE = eINSTANCE.getObjet_Taille();

    /**
     * The meta object literal for the '<em><b>Transformable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__TRANSFORMABLE = eINSTANCE.getObjet_Transformable();

    /**
     * The meta object literal for the '{@link game.game.impl.InteractionImpl <em>Interaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.InteractionImpl
     * @see game.game.impl.GamePackageImpl#getInteraction()
     * @generated
     */
    EClass INTERACTION = eINSTANCE.getInteraction();

    /**
     * The meta object literal for the '<em><b>Question</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION__QUESTION = eINSTANCE.getInteraction_Question();

    /**
     * The meta object literal for the '<em><b>Choix</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION__CHOIX = eINSTANCE.getInteraction_Choix();

    /**
     * The meta object literal for the '{@link game.game.impl.ChoixImpl <em>Choix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.ChoixImpl
     * @see game.game.impl.GamePackageImpl#getChoix()
     * @generated
     */
    EClass CHOIX = eINSTANCE.getChoix();

    /**
     * The meta object literal for the '<em><b>Numero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__NUMERO = eINSTANCE.getChoix_Numero();

    /**
     * The meta object literal for the '<em><b>Reponse</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__REPONSE = eINSTANCE.getChoix_Reponse();

    /**
     * The meta object literal for the '<em><b>Recompense</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__RECOMPENSE = eINSTANCE.getChoix_Recompense();

    /**
     * The meta object literal for the '{@link game.game.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.ConditionImpl
     * @see game.game.impl.GamePackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Connaissances Requises</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__CONNAISSANCES_REQUISES = eINSTANCE.getCondition_ConnaissancesRequises();

    /**
     * The meta object literal for the '<em><b>Objets Requis</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__OBJETS_REQUIS = eINSTANCE.getCondition_ObjetsRequis();

    /**
     * The meta object literal for the '{@link game.game.impl.RecompenseImpl <em>Recompense</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.impl.RecompenseImpl
     * @see game.game.impl.GamePackageImpl#getRecompense()
     * @generated
     */
    EClass RECOMPENSE = eINSTANCE.getRecompense();

    /**
     * The meta object literal for the '<em><b>Avantage</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECOMPENSE__AVANTAGE = eINSTANCE.getRecompense_Avantage();

    /**
     * The meta object literal for the '{@link game.game.Nature <em>Nature</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.game.Nature
     * @see game.game.impl.GamePackageImpl#getNature()
     * @generated
     */
    EEnum NATURE = eINSTANCE.getNature();

  }

} //GamePackage
