/**
 * generated by Xtext 2.23.0
 */
package game.game;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see game.game.GamePackage
 * @generated
 */
public interface GameFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameFactory eINSTANCE = game.game.impl.GameFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Jeu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Jeu</em>'.
   * @generated
   */
  Jeu createJeu();

  /**
   * Returns a new object of class '<em>Elements Jeu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Elements Jeu</em>'.
   * @generated
   */
  ElementsJeu createElementsJeu();

  /**
   * Returns a new object of class '<em>Place</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Place</em>'.
   * @generated
   */
  Place createPlace();

  /**
   * Returns a new object of class '<em>Avantage</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Avantage</em>'.
   * @generated
   */
  Avantage createAvantage();

  /**
   * Returns a new object of class '<em>Territoire</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Territoire</em>'.
   * @generated
   */
  Territoire createTerritoire();

  /**
   * Returns a new object of class '<em>Lieu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lieu</em>'.
   * @generated
   */
  Lieu createLieu();

  /**
   * Returns a new object of class '<em>Chemin</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chemin</em>'.
   * @generated
   */
  Chemin createChemin();

  /**
   * Returns a new object of class '<em>Personne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Personne</em>'.
   * @generated
   */
  Personne createPersonne();

  /**
   * Returns a new object of class '<em>Explorateur</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Explorateur</em>'.
   * @generated
   */
  Explorateur createExplorateur();

  /**
   * Returns a new object of class '<em>Connaissance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Connaissance</em>'.
   * @generated
   */
  Connaissance createConnaissance();

  /**
   * Returns a new object of class '<em>Objet</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Objet</em>'.
   * @generated
   */
  Objet createObjet();

  /**
   * Returns a new object of class '<em>Interaction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interaction</em>'.
   * @generated
   */
  Interaction createInteraction();

  /**
   * Returns a new object of class '<em>Choix</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Choix</em>'.
   * @generated
   */
  Choix createChoix();

  /**
   * Returns a new object of class '<em>Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition</em>'.
   * @generated
   */
  Condition createCondition();

  /**
   * Returns a new object of class '<em>Recompense</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Recompense</em>'.
   * @generated
   */
  Recompense createRecompense();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GamePackage getGamePackage();

} //GameFactory
