/**
 * generated by Xtext 2.23.0
 */
package game.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jeu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.game.Jeu#getNom <em>Nom</em>}</li>
 *   <li>{@link game.game.Jeu#getTerritoire <em>Territoire</em>}</li>
 *   <li>{@link game.game.Jeu#getExplorateur <em>Explorateur</em>}</li>
 *   <li>{@link game.game.Jeu#getElementsjeu <em>Elementsjeu</em>}</li>
 * </ul>
 *
 * @see game.game.GamePackage#getJeu()
 * @model
 * @generated
 */
public interface Jeu extends EObject
{
  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see game.game.GamePackage#getJeu_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link game.game.Jeu#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>Territoire</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Territoire</em>' containment reference.
   * @see #setTerritoire(Territoire)
   * @see game.game.GamePackage#getJeu_Territoire()
   * @model containment="true"
   * @generated
   */
  Territoire getTerritoire();

  /**
   * Sets the value of the '{@link game.game.Jeu#getTerritoire <em>Territoire</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Territoire</em>' containment reference.
   * @see #getTerritoire()
   * @generated
   */
  void setTerritoire(Territoire value);

  /**
   * Returns the value of the '<em><b>Explorateur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Explorateur</em>' containment reference.
   * @see #setExplorateur(Explorateur)
   * @see game.game.GamePackage#getJeu_Explorateur()
   * @model containment="true"
   * @generated
   */
  Explorateur getExplorateur();

  /**
   * Sets the value of the '{@link game.game.Jeu#getExplorateur <em>Explorateur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Explorateur</em>' containment reference.
   * @see #getExplorateur()
   * @generated
   */
  void setExplorateur(Explorateur value);

  /**
   * Returns the value of the '<em><b>Elementsjeu</b></em>' containment reference list.
   * The list contents are of type {@link game.game.ElementsJeu}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elementsjeu</em>' containment reference list.
   * @see game.game.GamePackage#getJeu_Elementsjeu()
   * @model containment="true"
   * @generated
   */
  EList<ElementsJeu> getElementsjeu();

} // Jeu
