/**
 * generated by Xtext 2.23.0
 */
package game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Place</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see game.game.GamePackage#getPlace()
 * @model
 * @generated
 */
public interface Place extends ElementsJeu
{
} // Place
