/*
 * generated by Xtext 2.23.0
 */
package game.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GameGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class JeuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Jeu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJeuKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTerritoireAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTerritoireTerritoireParserRuleCall_3_0 = (RuleCall)cTerritoireAssignment_3.eContents().get(0);
		private final Assignment cExplorateurAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExplorateurExplorateurParserRuleCall_4_0 = (RuleCall)cExplorateurAssignment_4.eContents().get(0);
		private final Assignment cElementsjeuAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cElementsjeuElementsJeuParserRuleCall_5_0 = (RuleCall)cElementsjeuAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Jeu:
		//	'jeu' name=ID '{'
		//	territoire=Territoire
		//	explorateur=Explorateur
		//	elementsjeu+=ElementsJeu*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'jeu' name=ID '{' territoire=Territoire explorateur=Explorateur elementsjeu+=ElementsJeu* '}'
		public Group getGroup() { return cGroup; }
		
		//'jeu'
		public Keyword getJeuKeyword_0() { return cJeuKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//territoire=Territoire
		public Assignment getTerritoireAssignment_3() { return cTerritoireAssignment_3; }
		
		//Territoire
		public RuleCall getTerritoireTerritoireParserRuleCall_3_0() { return cTerritoireTerritoireParserRuleCall_3_0; }
		
		//explorateur=Explorateur
		public Assignment getExplorateurAssignment_4() { return cExplorateurAssignment_4; }
		
		//Explorateur
		public RuleCall getExplorateurExplorateurParserRuleCall_4_0() { return cExplorateurExplorateurParserRuleCall_4_0; }
		
		//elementsjeu+=ElementsJeu*
		public Assignment getElementsjeuAssignment_5() { return cElementsjeuAssignment_5; }
		
		//ElementsJeu
		public RuleCall getElementsjeuElementsJeuParserRuleCall_5_0() { return cElementsjeuElementsJeuParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ElementsJeuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.ElementsJeu");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPersonneParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAvantageParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPlaceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ElementsJeu:
		//	Personne | Avantage | Place;
		@Override public ParserRule getRule() { return rule; }
		
		//Personne | Avantage | Place
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Personne
		public RuleCall getPersonneParserRuleCall_0() { return cPersonneParserRuleCall_0; }
		
		//Avantage
		public RuleCall getAvantageParserRuleCall_1() { return cAvantageParserRuleCall_1; }
		
		//Place
		public RuleCall getPlaceParserRuleCall_2() { return cPlaceParserRuleCall_2; }
	}
	public class PlaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Place");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLieuParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCheminParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Place:
		//	Lieu | Chemin;
		@Override public ParserRule getRule() { return rule; }
		
		//Lieu | Chemin
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Lieu
		public RuleCall getLieuParserRuleCall_0() { return cLieuParserRuleCall_0; }
		
		//Chemin
		public RuleCall getCheminParserRuleCall_1() { return cCheminParserRuleCall_1; }
	}
	public class AvantageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Avantage");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cConnaissanceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cObjetParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Avantage:
		//	Connaissance | Objet;
		@Override public ParserRule getRule() { return rule; }
		
		//Connaissance | Objet
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Connaissance
		public RuleCall getConnaissanceParserRuleCall_0() { return cConnaissanceParserRuleCall_0; }
		
		//Objet
		public RuleCall getObjetParserRuleCall_1() { return cObjetParserRuleCall_1; }
	}
	public class TerritoireElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Territoire");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTerritoireKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPlacesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPlacesPlaceParserRuleCall_2_0 = (RuleCall)cPlacesAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Territoire:
		//	'territoire' '{'
		//	places+=Place+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'territoire' '{' places+=Place+ '}'
		public Group getGroup() { return cGroup; }
		
		//'territoire'
		public Keyword getTerritoireKeyword_0() { return cTerritoireKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//places+=Place+
		public Assignment getPlacesAssignment_2() { return cPlacesAssignment_2; }
		
		//Place
		public RuleCall getPlacesPlaceParserRuleCall_2_0() { return cPlacesPlaceParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class LieuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Lieu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLieuKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNatureAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNatureNatureEnumRuleCall_3_0 = (RuleCall)cNatureAssignment_3.eContents().get(0);
		
		//Lieu:
		//	'lieu' name=ID ':' nature=Nature;
		@Override public ParserRule getRule() { return rule; }
		
		//'lieu' name=ID ':' nature=Nature
		public Group getGroup() { return cGroup; }
		
		//'lieu'
		public Keyword getLieuKeyword_0() { return cLieuKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//nature=Nature
		public Assignment getNatureAssignment_3() { return cNatureAssignment_3; }
		
		//Nature
		public RuleCall getNatureNatureEnumRuleCall_3_0() { return cNatureNatureEnumRuleCall_3_0; }
	}
	public class CheminElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Chemin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCheminKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPredAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cPredLieuCrossReference_4_0 = (CrossReference)cPredAssignment_4.eContents().get(0);
		private final RuleCall cPredLieuIDTerminalRuleCall_4_0_1 = (RuleCall)cPredLieuCrossReference_4_0.eContents().get(1);
		private final Keyword cVersKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSuccAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSuccLieuCrossReference_6_0 = (CrossReference)cSuccAssignment_6.eContents().get(0);
		private final RuleCall cSuccLieuIDTerminalRuleCall_6_0_1 = (RuleCall)cSuccLieuCrossReference_6_0.eContents().get(1);
		private final Keyword cVisibleKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cVisibleAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cVisibleConditionParserRuleCall_8_0 = (RuleCall)cVisibleAssignment_8.eContents().get(0);
		private final Keyword cObligatoireKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cObligatoireAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cObligatoireBOOLTerminalRuleCall_10_0 = (RuleCall)cObligatoireAssignment_10.eContents().get(0);
		private final Keyword cOuvertKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cOuvertAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cOuvertBOOLTerminalRuleCall_12_0 = (RuleCall)cOuvertAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Chemin:
		//	'chemin' name=ID '{'
		//	'de' pred=[Lieu]
		//	'vers' succ=[Lieu]
		//	'visible' visible=Condition
		//	'obligatoire' obligatoire=BOOL
		//	'ouvert' ouvert=BOOL
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'chemin' name=ID '{' 'de' pred=[Lieu] 'vers' succ=[Lieu] 'visible' visible=Condition 'obligatoire' obligatoire=BOOL
		//'ouvert' ouvert=BOOL '}'
		public Group getGroup() { return cGroup; }
		
		//'chemin'
		public Keyword getCheminKeyword_0() { return cCheminKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'de'
		public Keyword getDeKeyword_3() { return cDeKeyword_3; }
		
		//pred=[Lieu]
		public Assignment getPredAssignment_4() { return cPredAssignment_4; }
		
		//[Lieu]
		public CrossReference getPredLieuCrossReference_4_0() { return cPredLieuCrossReference_4_0; }
		
		//ID
		public RuleCall getPredLieuIDTerminalRuleCall_4_0_1() { return cPredLieuIDTerminalRuleCall_4_0_1; }
		
		//'vers'
		public Keyword getVersKeyword_5() { return cVersKeyword_5; }
		
		//succ=[Lieu]
		public Assignment getSuccAssignment_6() { return cSuccAssignment_6; }
		
		//[Lieu]
		public CrossReference getSuccLieuCrossReference_6_0() { return cSuccLieuCrossReference_6_0; }
		
		//ID
		public RuleCall getSuccLieuIDTerminalRuleCall_6_0_1() { return cSuccLieuIDTerminalRuleCall_6_0_1; }
		
		//'visible'
		public Keyword getVisibleKeyword_7() { return cVisibleKeyword_7; }
		
		//visible=Condition
		public Assignment getVisibleAssignment_8() { return cVisibleAssignment_8; }
		
		//Condition
		public RuleCall getVisibleConditionParserRuleCall_8_0() { return cVisibleConditionParserRuleCall_8_0; }
		
		//'obligatoire'
		public Keyword getObligatoireKeyword_9() { return cObligatoireKeyword_9; }
		
		//obligatoire=BOOL
		public Assignment getObligatoireAssignment_10() { return cObligatoireAssignment_10; }
		
		//BOOL
		public RuleCall getObligatoireBOOLTerminalRuleCall_10_0() { return cObligatoireBOOLTerminalRuleCall_10_0; }
		
		//'ouvert'
		public Keyword getOuvertKeyword_11() { return cOuvertKeyword_11; }
		
		//ouvert=BOOL
		public Assignment getOuvertAssignment_12() { return cOuvertAssignment_12; }
		
		//BOOL
		public RuleCall getOuvertBOOLTerminalRuleCall_12_0() { return cOuvertBOOLTerminalRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class PersonneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Personne");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonneKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLocalisationKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPlaceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cPlacePlaceCrossReference_4_0 = (CrossReference)cPlaceAssignment_4.eContents().get(0);
		private final RuleCall cPlacePlaceIDTerminalRuleCall_4_0_1 = (RuleCall)cPlacePlaceCrossReference_4_0.eContents().get(1);
		private final Keyword cVisibleKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cVisibleAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cVisibleConditionParserRuleCall_6_0 = (RuleCall)cVisibleAssignment_6.eContents().get(0);
		private final Keyword cActifKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cActifAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cActifConditionParserRuleCall_8_0 = (RuleCall)cActifAssignment_8.eContents().get(0);
		private final Keyword cObligatoireKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cObligatoireAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cObligatoireBOOLTerminalRuleCall_10_0 = (RuleCall)cObligatoireAssignment_10.eContents().get(0);
		private final Keyword cInteractionsKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cInteractionsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cInteractionsInteractionParserRuleCall_12_0 = (RuleCall)cInteractionsAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Personne:
		//	'personne' name=ID '{'
		//	'localisation' place=[Place]
		//	'visible' visible=Condition
		//	'actif' actif=Condition
		//	'obligatoire' obligatoire=BOOL
		//	'interactions' interactions+=Interaction*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'personne' name=ID '{' 'localisation' place=[Place] 'visible' visible=Condition 'actif' actif=Condition 'obligatoire'
		//obligatoire=BOOL 'interactions' interactions+=Interaction* '}'
		public Group getGroup() { return cGroup; }
		
		//'personne'
		public Keyword getPersonneKeyword_0() { return cPersonneKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'localisation'
		public Keyword getLocalisationKeyword_3() { return cLocalisationKeyword_3; }
		
		//place=[Place]
		public Assignment getPlaceAssignment_4() { return cPlaceAssignment_4; }
		
		//[Place]
		public CrossReference getPlacePlaceCrossReference_4_0() { return cPlacePlaceCrossReference_4_0; }
		
		//ID
		public RuleCall getPlacePlaceIDTerminalRuleCall_4_0_1() { return cPlacePlaceIDTerminalRuleCall_4_0_1; }
		
		//'visible'
		public Keyword getVisibleKeyword_5() { return cVisibleKeyword_5; }
		
		//visible=Condition
		public Assignment getVisibleAssignment_6() { return cVisibleAssignment_6; }
		
		//Condition
		public RuleCall getVisibleConditionParserRuleCall_6_0() { return cVisibleConditionParserRuleCall_6_0; }
		
		//'actif'
		public Keyword getActifKeyword_7() { return cActifKeyword_7; }
		
		//actif=Condition
		public Assignment getActifAssignment_8() { return cActifAssignment_8; }
		
		//Condition
		public RuleCall getActifConditionParserRuleCall_8_0() { return cActifConditionParserRuleCall_8_0; }
		
		//'obligatoire'
		public Keyword getObligatoireKeyword_9() { return cObligatoireKeyword_9; }
		
		//obligatoire=BOOL
		public Assignment getObligatoireAssignment_10() { return cObligatoireAssignment_10; }
		
		//BOOL
		public RuleCall getObligatoireBOOLTerminalRuleCall_10_0() { return cObligatoireBOOLTerminalRuleCall_10_0; }
		
		//'interactions'
		public Keyword getInteractionsKeyword_11() { return cInteractionsKeyword_11; }
		
		//interactions+=Interaction*
		public Assignment getInteractionsAssignment_12() { return cInteractionsAssignment_12; }
		
		//Interaction
		public RuleCall getInteractionsInteractionParserRuleCall_12_0() { return cInteractionsInteractionParserRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class ExplorateurElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Explorateur");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExplorateurKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLocalisationKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPlaceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPlacePlaceCrossReference_3_0 = (CrossReference)cPlaceAssignment_3.eContents().get(0);
		private final RuleCall cPlacePlaceIDTerminalRuleCall_3_0_1 = (RuleCall)cPlacePlaceCrossReference_3_0.eContents().get(1);
		private final Keyword cTailleKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cDisponibleKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTailleDispoAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTailleDispoINTTerminalRuleCall_6_0 = (RuleCall)cTailleDispoAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cObjetsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cPossedesKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cObjetsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cObjetsObjetParserRuleCall_7_2_0 = (RuleCall)cObjetsAssignment_7_2.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cConnaissancesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cPossedesKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cConnaissancesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cConnaissancesConnaissanceParserRuleCall_8_2_0 = (RuleCall)cConnaissancesAssignment_8_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Explorateur:
		//	'explorateur' '{'
		//	'localisation' place=[Place]
		//	'taille' 'disponible' tailleDispo=INT ('objets' 'possedes' objets+=Objet*)? ('connaissances' 'possedes'
		//	connaissances+=Connaissance*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'explorateur' '{' 'localisation' place=[Place] 'taille' 'disponible' tailleDispo=INT ('objets' 'possedes'
		//objets+=Objet*)? ('connaissances' 'possedes' connaissances+=Connaissance*)? '}'
		public Group getGroup() { return cGroup; }
		
		//'explorateur'
		public Keyword getExplorateurKeyword_0() { return cExplorateurKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'localisation'
		public Keyword getLocalisationKeyword_2() { return cLocalisationKeyword_2; }
		
		//place=[Place]
		public Assignment getPlaceAssignment_3() { return cPlaceAssignment_3; }
		
		//[Place]
		public CrossReference getPlacePlaceCrossReference_3_0() { return cPlacePlaceCrossReference_3_0; }
		
		//ID
		public RuleCall getPlacePlaceIDTerminalRuleCall_3_0_1() { return cPlacePlaceIDTerminalRuleCall_3_0_1; }
		
		//'taille'
		public Keyword getTailleKeyword_4() { return cTailleKeyword_4; }
		
		//'disponible'
		public Keyword getDisponibleKeyword_5() { return cDisponibleKeyword_5; }
		
		//tailleDispo=INT
		public Assignment getTailleDispoAssignment_6() { return cTailleDispoAssignment_6; }
		
		//INT
		public RuleCall getTailleDispoINTTerminalRuleCall_6_0() { return cTailleDispoINTTerminalRuleCall_6_0; }
		
		//('objets' 'possedes' objets+=Objet*)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'objets'
		public Keyword getObjetsKeyword_7_0() { return cObjetsKeyword_7_0; }
		
		//'possedes'
		public Keyword getPossedesKeyword_7_1() { return cPossedesKeyword_7_1; }
		
		//objets+=Objet*
		public Assignment getObjetsAssignment_7_2() { return cObjetsAssignment_7_2; }
		
		//Objet
		public RuleCall getObjetsObjetParserRuleCall_7_2_0() { return cObjetsObjetParserRuleCall_7_2_0; }
		
		//('connaissances' 'possedes' connaissances+=Connaissance*)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'connaissances'
		public Keyword getConnaissancesKeyword_8_0() { return cConnaissancesKeyword_8_0; }
		
		//'possedes'
		public Keyword getPossedesKeyword_8_1() { return cPossedesKeyword_8_1; }
		
		//connaissances+=Connaissance*
		public Assignment getConnaissancesAssignment_8_2() { return cConnaissancesAssignment_8_2; }
		
		//Connaissance
		public RuleCall getConnaissancesConnaissanceParserRuleCall_8_2_0() { return cConnaissancesConnaissanceParserRuleCall_8_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ConnaissanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Connaissance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnaissanceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cVisibleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVisibleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVisibleConditionParserRuleCall_4_0 = (RuleCall)cVisibleAssignment_4.eContents().get(0);
		private final Keyword cActifKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cActifAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cActifConditionParserRuleCall_6_0 = (RuleCall)cActifAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Connaissance:
		//	'connaissance' name=ID '{'
		//	'visible' visible=Condition
		//	'actif' actif=Condition
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'connaissance' name=ID '{' 'visible' visible=Condition 'actif' actif=Condition '}'
		public Group getGroup() { return cGroup; }
		
		//'connaissance'
		public Keyword getConnaissanceKeyword_0() { return cConnaissanceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'visible'
		public Keyword getVisibleKeyword_3() { return cVisibleKeyword_3; }
		
		//visible=Condition
		public Assignment getVisibleAssignment_4() { return cVisibleAssignment_4; }
		
		//Condition
		public RuleCall getVisibleConditionParserRuleCall_4_0() { return cVisibleConditionParserRuleCall_4_0; }
		
		//'actif'
		public Keyword getActifKeyword_5() { return cActifKeyword_5; }
		
		//actif=Condition
		public Assignment getActifAssignment_6() { return cActifAssignment_6; }
		
		//Condition
		public RuleCall getActifConditionParserRuleCall_6_0() { return cActifConditionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ObjetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Objet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cObjetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cVisibleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVisibleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVisibleConditionParserRuleCall_4_0 = (RuleCall)cVisibleAssignment_4.eContents().get(0);
		private final Keyword cActifKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cActifAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cActifConditionParserRuleCall_6_0 = (RuleCall)cActifAssignment_6.eContents().get(0);
		private final Keyword cQuantiteKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cQteAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cQteINTTerminalRuleCall_8_0 = (RuleCall)cQteAssignment_8.eContents().get(0);
		private final Keyword cTailleKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cTailleAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cTailleINTTerminalRuleCall_10_0 = (RuleCall)cTailleAssignment_10.eContents().get(0);
		private final Keyword cTransformableKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cTransformableAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cTransformableBOOLTerminalRuleCall_12_0 = (RuleCall)cTransformableAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Objet:
		//	'objet' name=ID '{'
		//	'visible' visible=Condition
		//	'actif' actif=Condition
		//	'quantite' qte=INT
		//	'taille' taille=INT
		//	'transformable' transformable=BOOL
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'objet' name=ID '{' 'visible' visible=Condition 'actif' actif=Condition 'quantite' qte=INT 'taille' taille=INT
		//'transformable' transformable=BOOL '}'
		public Group getGroup() { return cGroup; }
		
		//'objet'
		public Keyword getObjetKeyword_0() { return cObjetKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'visible'
		public Keyword getVisibleKeyword_3() { return cVisibleKeyword_3; }
		
		//visible=Condition
		public Assignment getVisibleAssignment_4() { return cVisibleAssignment_4; }
		
		//Condition
		public RuleCall getVisibleConditionParserRuleCall_4_0() { return cVisibleConditionParserRuleCall_4_0; }
		
		//'actif'
		public Keyword getActifKeyword_5() { return cActifKeyword_5; }
		
		//actif=Condition
		public Assignment getActifAssignment_6() { return cActifAssignment_6; }
		
		//Condition
		public RuleCall getActifConditionParserRuleCall_6_0() { return cActifConditionParserRuleCall_6_0; }
		
		//'quantite'
		public Keyword getQuantiteKeyword_7() { return cQuantiteKeyword_7; }
		
		//qte=INT
		public Assignment getQteAssignment_8() { return cQteAssignment_8; }
		
		//INT
		public RuleCall getQteINTTerminalRuleCall_8_0() { return cQteINTTerminalRuleCall_8_0; }
		
		//'taille'
		public Keyword getTailleKeyword_9() { return cTailleKeyword_9; }
		
		//taille=INT
		public Assignment getTailleAssignment_10() { return cTailleAssignment_10; }
		
		//INT
		public RuleCall getTailleINTTerminalRuleCall_10_0() { return cTailleINTTerminalRuleCall_10_0; }
		
		//'transformable'
		public Keyword getTransformableKeyword_11() { return cTransformableKeyword_11; }
		
		//transformable=BOOL
		public Assignment getTransformableAssignment_12() { return cTransformableAssignment_12; }
		
		//BOOL
		public RuleCall getTransformableBOOLTerminalRuleCall_12_0() { return cTransformableBOOLTerminalRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class InteractionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Interaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInteractionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cQuestionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cQuestionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQuestionSTRINGTerminalRuleCall_3_0 = (RuleCall)cQuestionAssignment_3.eContents().get(0);
		private final Assignment cChoixAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cChoixChoixParserRuleCall_4_0 = (RuleCall)cChoixAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Interaction:
		//	'interaction' '{'
		//	'question' question=STRING
		//	choix+=Choix+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'interaction' '{' 'question' question=STRING choix+=Choix+ '}'
		public Group getGroup() { return cGroup; }
		
		//'interaction'
		public Keyword getInteractionKeyword_0() { return cInteractionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'question'
		public Keyword getQuestionKeyword_2() { return cQuestionKeyword_2; }
		
		//question=STRING
		public Assignment getQuestionAssignment_3() { return cQuestionAssignment_3; }
		
		//STRING
		public RuleCall getQuestionSTRINGTerminalRuleCall_3_0() { return cQuestionSTRINGTerminalRuleCall_3_0; }
		
		//choix+=Choix+
		public Assignment getChoixAssignment_4() { return cChoixAssignment_4; }
		
		//Choix
		public RuleCall getChoixChoixParserRuleCall_4_0() { return cChoixChoixParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ChoixElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Choix");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoixKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNumeroAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumeroINTTerminalRuleCall_1_0 = (RuleCall)cNumeroAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cReponseKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cReponseAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cReponseSTRINGTerminalRuleCall_4_0 = (RuleCall)cReponseAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Alternatives cAlternatives_5_0 = (Alternatives)cGroup_5.eContents().get(0);
		private final Keyword cConsommeKeyword_5_0_0 = (Keyword)cAlternatives_5_0.eContents().get(0);
		private final Keyword cDonneKeyword_5_0_1 = (Keyword)cAlternatives_5_0.eContents().get(1);
		private final Assignment cQteAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cQteINTTerminalRuleCall_5_1_0 = (RuleCall)cQteAssignment_5_1.eContents().get(0);
		private final Assignment cAvantageAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cAvantageAvantageCrossReference_5_2_0 = (CrossReference)cAvantageAssignment_5_2.eContents().get(0);
		private final RuleCall cAvantageAvantageIDTerminalRuleCall_5_2_0_1 = (RuleCall)cAvantageAvantageCrossReference_5_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Choix:
		//	'choix' numero=INT '{'
		//	'reponse' reponse=STRING (('consomme' | 'donne') qte+=INT avantage+=[Avantage])*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'choix' numero=INT '{' 'reponse' reponse=STRING (('consomme' | 'donne') qte+=INT avantage+=[Avantage])* '}'
		public Group getGroup() { return cGroup; }
		
		//'choix'
		public Keyword getChoixKeyword_0() { return cChoixKeyword_0; }
		
		//numero=INT
		public Assignment getNumeroAssignment_1() { return cNumeroAssignment_1; }
		
		//INT
		public RuleCall getNumeroINTTerminalRuleCall_1_0() { return cNumeroINTTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'reponse'
		public Keyword getReponseKeyword_3() { return cReponseKeyword_3; }
		
		//reponse=STRING
		public Assignment getReponseAssignment_4() { return cReponseAssignment_4; }
		
		//STRING
		public RuleCall getReponseSTRINGTerminalRuleCall_4_0() { return cReponseSTRINGTerminalRuleCall_4_0; }
		
		//(('consomme' | 'donne') qte+=INT avantage+=[Avantage])*
		public Group getGroup_5() { return cGroup_5; }
		
		//('consomme' | 'donne')
		public Alternatives getAlternatives_5_0() { return cAlternatives_5_0; }
		
		//'consomme'
		public Keyword getConsommeKeyword_5_0_0() { return cConsommeKeyword_5_0_0; }
		
		//'donne'
		public Keyword getDonneKeyword_5_0_1() { return cDonneKeyword_5_0_1; }
		
		//qte+=INT
		public Assignment getQteAssignment_5_1() { return cQteAssignment_5_1; }
		
		//INT
		public RuleCall getQteINTTerminalRuleCall_5_1_0() { return cQteINTTerminalRuleCall_5_1_0; }
		
		//avantage+=[Avantage]
		public Assignment getAvantageAssignment_5_2() { return cAvantageAssignment_5_2; }
		
		//[Avantage]
		public CrossReference getAvantageAvantageCrossReference_5_2_0() { return cAvantageAvantageCrossReference_5_2_0; }
		
		//ID
		public RuleCall getAvantageAvantageIDTerminalRuleCall_5_2_0_1() { return cAvantageAvantageIDTerminalRuleCall_5_2_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Condition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cConditionKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_0_3 = (Group)cGroup_0.eContents().get(3);
		private final Keyword cConnaissancesKeyword_0_3_0 = (Keyword)cGroup_0_3.eContents().get(0);
		private final Alternatives cAlternatives_0_3_1 = (Alternatives)cGroup_0_3.eContents().get(1);
		private final Group cGroup_0_3_1_0 = (Group)cAlternatives_0_3_1.eContents().get(0);
		private final Keyword cRequisesKeyword_0_3_1_0_0 = (Keyword)cGroup_0_3_1_0.eContents().get(0);
		private final Assignment cConnaissancesRequisesAssignment_0_3_1_0_1 = (Assignment)cGroup_0_3_1_0.eContents().get(1);
		private final CrossReference cConnaissancesRequisesConnaissanceCrossReference_0_3_1_0_1_0 = (CrossReference)cConnaissancesRequisesAssignment_0_3_1_0_1.eContents().get(0);
		private final RuleCall cConnaissancesRequisesConnaissanceIDTerminalRuleCall_0_3_1_0_1_0_1 = (RuleCall)cConnaissancesRequisesConnaissanceCrossReference_0_3_1_0_1_0.eContents().get(1);
		private final Group cGroup_0_3_1_1 = (Group)cAlternatives_0_3_1.eContents().get(1);
		private final Keyword cInterditesKeyword_0_3_1_1_0 = (Keyword)cGroup_0_3_1_1.eContents().get(0);
		private final Assignment cConnaissancesInterditesAssignment_0_3_1_1_1 = (Assignment)cGroup_0_3_1_1.eContents().get(1);
		private final CrossReference cConnaissancesInterditesConnaissanceCrossReference_0_3_1_1_1_0 = (CrossReference)cConnaissancesInterditesAssignment_0_3_1_1_1.eContents().get(0);
		private final RuleCall cConnaissancesInterditesConnaissanceIDTerminalRuleCall_0_3_1_1_1_0_1 = (RuleCall)cConnaissancesInterditesConnaissanceCrossReference_0_3_1_1_1_0.eContents().get(1);
		private final Group cGroup_0_4 = (Group)cGroup_0.eContents().get(4);
		private final Assignment cQuantiteAssignment_0_4_0 = (Assignment)cGroup_0_4.eContents().get(0);
		private final RuleCall cQuantiteINTTerminalRuleCall_0_4_0_0 = (RuleCall)cQuantiteAssignment_0_4_0.eContents().get(0);
		private final Keyword cObjetsKeyword_0_4_1 = (Keyword)cGroup_0_4.eContents().get(1);
		private final Alternatives cAlternatives_0_4_2 = (Alternatives)cGroup_0_4.eContents().get(2);
		private final Group cGroup_0_4_2_0 = (Group)cAlternatives_0_4_2.eContents().get(0);
		private final Keyword cRequisKeyword_0_4_2_0_0 = (Keyword)cGroup_0_4_2_0.eContents().get(0);
		private final Assignment cObjetsRequisAssignment_0_4_2_0_1 = (Assignment)cGroup_0_4_2_0.eContents().get(1);
		private final CrossReference cObjetsRequisObjetCrossReference_0_4_2_0_1_0 = (CrossReference)cObjetsRequisAssignment_0_4_2_0_1.eContents().get(0);
		private final RuleCall cObjetsRequisObjetIDTerminalRuleCall_0_4_2_0_1_0_1 = (RuleCall)cObjetsRequisObjetCrossReference_0_4_2_0_1_0.eContents().get(1);
		private final Group cGroup_0_4_2_1 = (Group)cAlternatives_0_4_2.eContents().get(1);
		private final Keyword cInterditsKeyword_0_4_2_1_0 = (Keyword)cGroup_0_4_2_1.eContents().get(0);
		private final Assignment cObjetsInterditsAssignment_0_4_2_1_1 = (Assignment)cGroup_0_4_2_1.eContents().get(1);
		private final CrossReference cObjetsInterditsObjetCrossReference_0_4_2_1_1_0 = (CrossReference)cObjetsInterditsAssignment_0_4_2_1_1.eContents().get(0);
		private final RuleCall cObjetsInterditsObjetIDTerminalRuleCall_0_4_2_1_1_0_1 = (RuleCall)cObjetsInterditsObjetCrossReference_0_4_2_1_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_0_5 = (Keyword)cGroup_0.eContents().get(5);
		private final RuleCall cBOOLTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Condition:
		//	'condition' name=ID '{' ('connaissances' ('requises' connaissancesRequises+=[Connaissance]* | 'interdites'
		//	connaissancesInterdites+=[Connaissance]*))* (quantite=INT 'objets' ('requis' objetsRequis+=[Objet]* | 'interdits'
		//	objetsInterdits+=[Objet]*))*
		//	'}' | BOOL;
		@Override public ParserRule getRule() { return rule; }
		
		//'condition' name=ID '{' ('connaissances' ('requises' connaissancesRequises+=[Connaissance]* | 'interdites'
		//connaissancesInterdites+=[Connaissance]*))* (quantite=INT 'objets' ('requis' objetsRequis+=[Objet]* | 'interdits'
		//objetsInterdits+=[Objet]*))* '}' | BOOL
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'condition' name=ID '{' ('connaissances' ('requises' connaissancesRequises+=[Connaissance]* | 'interdites'
		//connaissancesInterdites+=[Connaissance]*))* (quantite=INT 'objets' ('requis' objetsRequis+=[Objet]* | 'interdits'
		//objetsInterdits+=[Objet]*))* '}'
		public Group getGroup_0() { return cGroup_0; }
		
		//'condition'
		public Keyword getConditionKeyword_0_0() { return cConditionKeyword_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0() { return cNameIDTerminalRuleCall_0_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0_2() { return cLeftCurlyBracketKeyword_0_2; }
		
		//('connaissances' ('requises' connaissancesRequises+=[Connaissance]* | 'interdites'
		//connaissancesInterdites+=[Connaissance]*))*
		public Group getGroup_0_3() { return cGroup_0_3; }
		
		//'connaissances'
		public Keyword getConnaissancesKeyword_0_3_0() { return cConnaissancesKeyword_0_3_0; }
		
		//('requises' connaissancesRequises+=[Connaissance]* | 'interdites' connaissancesInterdites+=[Connaissance]*)
		public Alternatives getAlternatives_0_3_1() { return cAlternatives_0_3_1; }
		
		//'requises' connaissancesRequises+=[Connaissance]*
		public Group getGroup_0_3_1_0() { return cGroup_0_3_1_0; }
		
		//'requises'
		public Keyword getRequisesKeyword_0_3_1_0_0() { return cRequisesKeyword_0_3_1_0_0; }
		
		//connaissancesRequises+=[Connaissance]*
		public Assignment getConnaissancesRequisesAssignment_0_3_1_0_1() { return cConnaissancesRequisesAssignment_0_3_1_0_1; }
		
		//[Connaissance]
		public CrossReference getConnaissancesRequisesConnaissanceCrossReference_0_3_1_0_1_0() { return cConnaissancesRequisesConnaissanceCrossReference_0_3_1_0_1_0; }
		
		//ID
		public RuleCall getConnaissancesRequisesConnaissanceIDTerminalRuleCall_0_3_1_0_1_0_1() { return cConnaissancesRequisesConnaissanceIDTerminalRuleCall_0_3_1_0_1_0_1; }
		
		//'interdites' connaissancesInterdites+=[Connaissance]*
		public Group getGroup_0_3_1_1() { return cGroup_0_3_1_1; }
		
		//'interdites'
		public Keyword getInterditesKeyword_0_3_1_1_0() { return cInterditesKeyword_0_3_1_1_0; }
		
		//connaissancesInterdites+=[Connaissance]*
		public Assignment getConnaissancesInterditesAssignment_0_3_1_1_1() { return cConnaissancesInterditesAssignment_0_3_1_1_1; }
		
		//[Connaissance]
		public CrossReference getConnaissancesInterditesConnaissanceCrossReference_0_3_1_1_1_0() { return cConnaissancesInterditesConnaissanceCrossReference_0_3_1_1_1_0; }
		
		//ID
		public RuleCall getConnaissancesInterditesConnaissanceIDTerminalRuleCall_0_3_1_1_1_0_1() { return cConnaissancesInterditesConnaissanceIDTerminalRuleCall_0_3_1_1_1_0_1; }
		
		//(quantite=INT 'objets' ('requis' objetsRequis+=[Objet]* | 'interdits' objetsInterdits+=[Objet]*))*
		public Group getGroup_0_4() { return cGroup_0_4; }
		
		//quantite=INT
		public Assignment getQuantiteAssignment_0_4_0() { return cQuantiteAssignment_0_4_0; }
		
		//INT
		public RuleCall getQuantiteINTTerminalRuleCall_0_4_0_0() { return cQuantiteINTTerminalRuleCall_0_4_0_0; }
		
		//'objets'
		public Keyword getObjetsKeyword_0_4_1() { return cObjetsKeyword_0_4_1; }
		
		//('requis' objetsRequis+=[Objet]* | 'interdits' objetsInterdits+=[Objet]*)
		public Alternatives getAlternatives_0_4_2() { return cAlternatives_0_4_2; }
		
		//'requis' objetsRequis+=[Objet]*
		public Group getGroup_0_4_2_0() { return cGroup_0_4_2_0; }
		
		//'requis'
		public Keyword getRequisKeyword_0_4_2_0_0() { return cRequisKeyword_0_4_2_0_0; }
		
		//objetsRequis+=[Objet]*
		public Assignment getObjetsRequisAssignment_0_4_2_0_1() { return cObjetsRequisAssignment_0_4_2_0_1; }
		
		//[Objet]
		public CrossReference getObjetsRequisObjetCrossReference_0_4_2_0_1_0() { return cObjetsRequisObjetCrossReference_0_4_2_0_1_0; }
		
		//ID
		public RuleCall getObjetsRequisObjetIDTerminalRuleCall_0_4_2_0_1_0_1() { return cObjetsRequisObjetIDTerminalRuleCall_0_4_2_0_1_0_1; }
		
		//'interdits' objetsInterdits+=[Objet]*
		public Group getGroup_0_4_2_1() { return cGroup_0_4_2_1; }
		
		//'interdits'
		public Keyword getInterditsKeyword_0_4_2_1_0() { return cInterditsKeyword_0_4_2_1_0; }
		
		//objetsInterdits+=[Objet]*
		public Assignment getObjetsInterditsAssignment_0_4_2_1_1() { return cObjetsInterditsAssignment_0_4_2_1_1; }
		
		//[Objet]
		public CrossReference getObjetsInterditsObjetCrossReference_0_4_2_1_1_0() { return cObjetsInterditsObjetCrossReference_0_4_2_1_1_0; }
		
		//ID
		public RuleCall getObjetsInterditsObjetIDTerminalRuleCall_0_4_2_1_1_0_1() { return cObjetsInterditsObjetIDTerminalRuleCall_0_4_2_1_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_0_5() { return cRightCurlyBracketKeyword_0_5; }
		
		//BOOL
		public RuleCall getBOOLTerminalRuleCall_1() { return cBOOLTerminalRuleCall_1; }
	}
	
	public class NatureElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.Nature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDepartEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDepartDepartKeyword_0_0 = (Keyword)cDepartEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFinEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFinFinKeyword_1_0 = (Keyword)cFinEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cInterEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cInterIntermediaireKeyword_2_0 = (Keyword)cInterEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Nature:
		//	depart | fin | inter='intermediaire';
		public EnumRule getRule() { return rule; }
		
		//depart | fin | inter='intermediaire'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//depart
		public EnumLiteralDeclaration getDepartEnumLiteralDeclaration_0() { return cDepartEnumLiteralDeclaration_0; }
		
		//'depart'
		public Keyword getDepartDepartKeyword_0_0() { return cDepartDepartKeyword_0_0; }
		
		//fin
		public EnumLiteralDeclaration getFinEnumLiteralDeclaration_1() { return cFinEnumLiteralDeclaration_1; }
		
		//'fin'
		public Keyword getFinFinKeyword_1_0() { return cFinFinKeyword_1_0; }
		
		//inter='intermediaire'
		public EnumLiteralDeclaration getInterEnumLiteralDeclaration_2() { return cInterEnumLiteralDeclaration_2; }
		
		//'intermediaire'
		public Keyword getInterIntermediaireKeyword_2_0() { return cInterIntermediaireKeyword_2_0; }
	}
	
	private final JeuElements pJeu;
	private final NatureElements eNature;
	private final TerminalRule tBOOL;
	private final ElementsJeuElements pElementsJeu;
	private final PlaceElements pPlace;
	private final AvantageElements pAvantage;
	private final TerritoireElements pTerritoire;
	private final LieuElements pLieu;
	private final CheminElements pChemin;
	private final PersonneElements pPersonne;
	private final ExplorateurElements pExplorateur;
	private final ConnaissanceElements pConnaissance;
	private final ObjetElements pObjet;
	private final InteractionElements pInteraction;
	private final ChoixElements pChoix;
	private final ConditionElements pCondition;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GameGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pJeu = new JeuElements();
		this.eNature = new NatureElements();
		this.tBOOL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "game.Game.BOOL");
		this.pElementsJeu = new ElementsJeuElements();
		this.pPlace = new PlaceElements();
		this.pAvantage = new AvantageElements();
		this.pTerritoire = new TerritoireElements();
		this.pLieu = new LieuElements();
		this.pChemin = new CheminElements();
		this.pPersonne = new PersonneElements();
		this.pExplorateur = new ExplorateurElements();
		this.pConnaissance = new ConnaissanceElements();
		this.pObjet = new ObjetElements();
		this.pInteraction = new InteractionElements();
		this.pChoix = new ChoixElements();
		this.pCondition = new ConditionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("game.Game".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Jeu:
	//	'jeu' name=ID '{'
	//	territoire=Territoire
	//	explorateur=Explorateur
	//	elementsjeu+=ElementsJeu*
	//	'}';
	public JeuElements getJeuAccess() {
		return pJeu;
	}
	
	public ParserRule getJeuRule() {
		return getJeuAccess().getRule();
	}
	
	//enum Nature:
	//	depart | fin | inter='intermediaire';
	public NatureElements getNatureAccess() {
		return eNature;
	}
	
	public EnumRule getNatureRule() {
		return getNatureAccess().getRule();
	}
	
	//terminal BOOL returns ecore::EBoolean:
	//	'true' | 'false';
	public TerminalRule getBOOLRule() {
		return tBOOL;
	}
	
	//ElementsJeu:
	//	Personne | Avantage | Place;
	public ElementsJeuElements getElementsJeuAccess() {
		return pElementsJeu;
	}
	
	public ParserRule getElementsJeuRule() {
		return getElementsJeuAccess().getRule();
	}
	
	//Place:
	//	Lieu | Chemin;
	public PlaceElements getPlaceAccess() {
		return pPlace;
	}
	
	public ParserRule getPlaceRule() {
		return getPlaceAccess().getRule();
	}
	
	//Avantage:
	//	Connaissance | Objet;
	public AvantageElements getAvantageAccess() {
		return pAvantage;
	}
	
	public ParserRule getAvantageRule() {
		return getAvantageAccess().getRule();
	}
	
	//Territoire:
	//	'territoire' '{'
	//	places+=Place+
	//	'}';
	public TerritoireElements getTerritoireAccess() {
		return pTerritoire;
	}
	
	public ParserRule getTerritoireRule() {
		return getTerritoireAccess().getRule();
	}
	
	//Lieu:
	//	'lieu' name=ID ':' nature=Nature;
	public LieuElements getLieuAccess() {
		return pLieu;
	}
	
	public ParserRule getLieuRule() {
		return getLieuAccess().getRule();
	}
	
	//Chemin:
	//	'chemin' name=ID '{'
	//	'de' pred=[Lieu]
	//	'vers' succ=[Lieu]
	//	'visible' visible=Condition
	//	'obligatoire' obligatoire=BOOL
	//	'ouvert' ouvert=BOOL
	//	'}';
	public CheminElements getCheminAccess() {
		return pChemin;
	}
	
	public ParserRule getCheminRule() {
		return getCheminAccess().getRule();
	}
	
	//Personne:
	//	'personne' name=ID '{'
	//	'localisation' place=[Place]
	//	'visible' visible=Condition
	//	'actif' actif=Condition
	//	'obligatoire' obligatoire=BOOL
	//	'interactions' interactions+=Interaction*
	//	'}';
	public PersonneElements getPersonneAccess() {
		return pPersonne;
	}
	
	public ParserRule getPersonneRule() {
		return getPersonneAccess().getRule();
	}
	
	//Explorateur:
	//	'explorateur' '{'
	//	'localisation' place=[Place]
	//	'taille' 'disponible' tailleDispo=INT ('objets' 'possedes' objets+=Objet*)? ('connaissances' 'possedes'
	//	connaissances+=Connaissance*)?
	//	'}';
	public ExplorateurElements getExplorateurAccess() {
		return pExplorateur;
	}
	
	public ParserRule getExplorateurRule() {
		return getExplorateurAccess().getRule();
	}
	
	//Connaissance:
	//	'connaissance' name=ID '{'
	//	'visible' visible=Condition
	//	'actif' actif=Condition
	//	'}';
	public ConnaissanceElements getConnaissanceAccess() {
		return pConnaissance;
	}
	
	public ParserRule getConnaissanceRule() {
		return getConnaissanceAccess().getRule();
	}
	
	//Objet:
	//	'objet' name=ID '{'
	//	'visible' visible=Condition
	//	'actif' actif=Condition
	//	'quantite' qte=INT
	//	'taille' taille=INT
	//	'transformable' transformable=BOOL
	//	'}';
	public ObjetElements getObjetAccess() {
		return pObjet;
	}
	
	public ParserRule getObjetRule() {
		return getObjetAccess().getRule();
	}
	
	//Interaction:
	//	'interaction' '{'
	//	'question' question=STRING
	//	choix+=Choix+
	//	'}';
	public InteractionElements getInteractionAccess() {
		return pInteraction;
	}
	
	public ParserRule getInteractionRule() {
		return getInteractionAccess().getRule();
	}
	
	//Choix:
	//	'choix' numero=INT '{'
	//	'reponse' reponse=STRING (('consomme' | 'donne') qte+=INT avantage+=[Avantage])*
	//	'}';
	public ChoixElements getChoixAccess() {
		return pChoix;
	}
	
	public ParserRule getChoixRule() {
		return getChoixAccess().getRule();
	}
	
	//Condition:
	//	'condition' name=ID '{' ('connaissances' ('requises' connaissancesRequises+=[Connaissance]* | 'interdites'
	//	connaissancesInterdites+=[Connaissance]*))* (quantite=INT 'objets' ('requis' objetsRequis+=[Objet]* | 'interdits'
	//	objetsInterdits+=[Objet]*))*
	//	'}' | BOOL;
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
