/**
 * generated by Xtext 2.23.0
 */
package game.game.impl;

import game.game.Connaissance;
import game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Connaissance</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConnaissanceImpl extends AvantageImpl implements Connaissance
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnaissanceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.CONNAISSANCE;
  }

} //ConnaissanceImpl
