/**
 * generated by Xtext 2.23.0
 */
package game.game.impl;

import game.game.ElementsJeu;
import game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Elements Jeu</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ElementsJeuImpl extends MinimalEObjectImpl.Container implements ElementsJeu
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementsJeuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.ELEMENTS_JEU;
  }

} //ElementsJeuImpl
