/**
 * generated by Xtext 2.23.0
 */
package game.game.impl;

import game.game.GamePackage;
import game.game.Place;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Place</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PlaceImpl extends ElementsJeuImpl implements Place
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PlaceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.PLACE;
  }

} //PlaceImpl
