/*
 * generated by Xtext 2.23.0
 */
package game.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameScopeProvider extends DelegatingScopeProvider {
}
